### PR TITLE
fix(Improvement): Change commit url+/commit/+ hash  to full hash for …

### PR DESCRIPTION
**Pull request by Aaltuj**
…usage with Git hosted by TFS, but use short hash for text shown to user

### CODE REVIEW

**Comment by robinjoseph08** [comment]
Hey @Aaltuj, thanks for the contribution! This is definitely something we can merge in!

Sorry for the failing build on Travis. We recently updated our linter and it was causing some issues, but it's been fixed in our master branch so if you rebase off of it, it should fix the build.

You also don't need to update the changelog yourself. Whenever we release a new version (which would be after merging your PR), we'll update the changelog, create a new git tag, and then publish it to npm. So you can remove the second commit you have that updates it. This way, we can include all of the commits within the version.

We'd also prefer to keep the `package.json` referring the primary upstream repo as opposed to a fork, in addition to leaving the author as Lob. Could you remove your refactor commit as well? Thanks!

**Comment by Aaltuj** [comment]
Just merged and deleted your requested changes. and build passes 
:)

**Comment by robinjoseph08** [comment]
Perfect, thanks!

**Comment by robinjoseph08** [comment]
Version 1.0.1 has been published!

**Pull request merged**
